apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-app-deployment
  namespace: e-store
spec:
  selector:
    matchLabels:
      app: analytics-app-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: analytics-app-deployment
    spec:
      containers:
        - name: analytics-app-container
          image: rso6315/analytics-service:latest
          ports:
            - containerPort: 8080
          env:
            - name: KUMULUZEE_SERVER_BASE-URL
              value: http:/34.89.139.199/analytics-service
            - name: KUMULUZEE_DISCOVERY_CLUSTER
              value: second-cluster
            - name: KUMULUZEE_DISCOVERY_CONSUL_AGENT
              value: http://consul-service-consul-server.e-store:8500
            - name: KUMULUZEE_CONFIG_CONSUL_AGENT
              value: http://consul-service-consul-server.e-store:8500
            - name: KUMULUZEE_DATASOURCES0_CONNECTIONURL
              value: jdbc:postgresql://analytics-db.e-store:5432/analytics
            - name: KUMULUZEE_DATASOURCES0_USERNAME
              value: postgres
            - name: KUMULUZEE_DATASOURCES0_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: analytics-pass
                  key: POSTGRES_PASSWORD
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: analytics-service
  name: analytics-service
  namespace: e-store
spec:
  type: NodePort
  ports:
    - port: 8080
      nodePort: 31016
      targetPort: 8080
      protocol: TCP
  selector:
    app: analytics-app-deployment
