apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-db-deployment
  namespace: e-store
spec:
  selector:
    matchLabels:
      app: analytics-db-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: analytics-db-deployment
    spec:
      containers:
        - name: postgres
          image: postgres:12
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_DB
              value: analytics
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: analytics-pass
                  key: POSTGRES_PASSWORD
          volumeMounts:
            - name: analytics-db-volume
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: analytics-db-volume
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: analytics-db
  name: analytics-db
  namespace: e-store
spec:
  type: ClusterIP
  ports:
    - port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    app: analytics-db-deployment
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: analytics-db-volume
  labels:
    type: local
  namespace: e-store
spec:
  storageClassName: manual
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data